# Generated by Django 4.0.6 on 2022-07-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0002_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
